services:
  frontend:
    build:
      context: ./no-me-atrevi-a-decirtelo
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./no-me-atrevi-a-decirtelo:/app
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app

  mongo: #Servidor de base de datos
    image: mongo:latest
    container_name: mongo-nma
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db # Volumen gestionado por docker =! carpeta en local mapeada

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-nma
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo # Se usa el nombre del servicio

volumes:
  mongo_data: 